steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chatgpt-line-bot', '.']
    env:
      - 'LINE_CHANNEL_SECRET=${_LINE_CHANNEL_SECRET}'
      - 'LINE_CHANNEL_ACCESS_TOKEN=${_LINE_CHANNEL_ACCESS_TOKEN}'
      - 'YOUTUBE_API_KEY=${_YOUTUBE_API_KEY}'
      - 'SERPAPI_API_KEY=${_SERPAPI_API_KEY}'
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/chatgpt-line-bot'

options:
  logging: CLOUD_LOGGING_ONLY