# 使用官方 Python 運行時作為父映像
FROM python:3.10-slim

# 設定工作目錄
WORKDIR /app

# 複製項目文件
COPY . .

# 安裝依賴
RUN pip install -r requirements.txt

# 接收建構參數
ARG LINE_CHANNEL_SECRET
ARG LINE_CHANNEL_ACCESS_TOKEN
ARG YOUTUBE_API_KEY
ARG SERPAPI_API_KEY
ARG OPENAI_API_KEY

# 設定環境變數
ENV PORT=8080
ENV LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
ENV LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
ENV SERPAPI_API_KEY=${SERPAPI_API_KEY}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

# 運行應用
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]